import { AttendanceRecord, LeaveApplication } from "@/types/attendance";

export const INITIAL_ATTENDANCE: AttendanceRecord[] = [
  {
    id: "att-1",
    userId: "USR-001",
    userName: "홍길동",
    department: "생산팀",
    position: "과장",
    date: "2026-09-07",
    checkIn: "08:45:12",
    status: "NORMAL",
    ipAddress: "192.168.0.21 (사내망)",
    location: "AMK 제1공장",
    workHours: 5.5,
  },
  {
    id: "att-2",
    userId: "USR-002",
    userName: "김철수",
    department: "생산팀",
    position: "대리",
    date: "2026-09-07",
    checkIn: "08:52:40",
    status: "NORMAL",
    ipAddress: "192.168.0.45 (사내망)",
    location: "AMK 제1공장 조립동",
    workHours: 5.3,
  },
  {
    id: "att-3",
    userId: "USR-003",
    userName: "이영희",
    department: "자재팀",
    position: "과장",
    date: "2026-09-07",
    checkIn: "09:12:05",
    status: "LATE",
    ipAddress: "192.168.0.88 (사내망)",
    location: "AMK 본관 2층",
    note: "부품 협력업체 유선 통화로 지각 체크인",
    workHours: 5.0,
  },
  {
    id: "att-4",
    userId: "USR-004",
    userName: "박민수",
    department: "영업팀",
    position: "차장",
    date: "2026-09-07",
    checkIn: "09:30:00",
    status: "FIELD_WORK",
    ipAddress: "외부 LTE / 모바일",
    location: "수원 거래처 납품 미팅",
    note: "거래처 현장 실사 및 납기 협의",
    workHours: 4.7,
  },
  {
    id: "att-5",
    userId: "USR-005",
    userName: "정재훈",
    department: "품질팀",
    position: "대리",
    date: "2026-09-07",
    status: "ON_LEAVE",
    note: "정기 연차 사용",
  },
];

export const INITIAL_LEAVES: LeaveApplication[] = [
  {
    id: "leave-1",
    userId: "USR-005",
    userName: "정재훈",
    department: "품질팀",
    leaveType: "ANNUAL",
    startDate: "2026-09-07",
    endDate: "2026-09-07",
    days: 1.0,
    reason: "개인 사유 (병원 진료 및 정기 연차)",
    status: "APPROVED",
    approverName: "최유진 팀장",
    appliedAt: "2026-09-05",
  },
  {
    id: "leave-2",
    userId: "USR-002",
    userName: "김철수",
    department: "생산팀",
    leaveType: "HALF_PM",
    startDate: "2026-09-09",
    endDate: "2026-09-09",
    days: 0.5,
    reason: "오후 반차 (가족 행사)",
    status: "PENDING",
    appliedAt: "2026-09-07",
  },
  {
    id: "leave-3",
    userId: "USR-004",
    userName: "박민수",
    department: "영업팀",
    leaveType: "FIELD_WORK",
    startDate: "2026-09-10",
    endDate: "2026-09-10",
    days: 1.0,
    reason: "화성 협력업체 품질 평가 출장",
    status: "PENDING",
    appliedAt: "2026-09-07",
  }
];