import { TaskItem } from "@/types/task";

export const INITIAL_TASKS: TaskItem[] = [
  {
    id: "task-1",
    title: "[생산1팀] 볼트 M4 규격 조립 라인 투입",
    description: "amk-inventory 연동 자재코드 MAT-BOLT-M4 출고 확인 후 1차 조립 진행",
    startDate: "2026-09-07T09:00",
    endDate: "2026-09-07T12:00",
    allDay: false,
    status: "IN_PROGRESS",
    priority: "HIGH",
    color: "#3b82f6",
    assigneeName: "김철수 대리",
    department: "생산팀",
    tags: ["생산", "자재투입", "긴급"],
    linkedItemCode: "MAT-BOLT-M4",
  },
  {
    id: "task-2",
    title: "[자재관리] amk-inventory 안전재고 부족 품목 발주 회의",
    description: "안전재고 미달 4개 품목에 대한 긴급 발주 및 납기 조율",
    startDate: "2026-09-07T14:00",
    endDate: "2026-09-07T15:30",
    allDay: false,
    status: "TODO",
    priority: "URGENT",
    color: "#ef4444",
    assigneeName: "이영희 과장",
    department: "자재팀",
    tags: ["재고", "회의", "발주"],
    linkedItemCode: "PART-SEAL-01",
  },
  {
    id: "task-3",
    title: "[영업관리] AMK 3분기 납품 계약 일정 전사 공유",
    description: "납품처 출하 일정 캘린더 등록 및 납기 검토",
    startDate: "2026-09-08T10:00",
    endDate: "2026-09-08T11:30",
    allDay: false,
    status: "TODO",
    priority: "MEDIUM",
    color: "#10b981",
    assigneeName: "박민수 차장",
    department: "영업팀",
    tags: ["영업", "계약"],
  },
  {
    id: "task-4",
    title: "[품질관리] 완성품 QA 검사 및 테스트 성적서 작성",
    description: "1차 양산품 내구성 테스트 및 인증서 첨부",
    startDate: "2026-09-09T13:00",
    endDate: "2026-09-09T18:00",
    allDay: false,
    status: "REVIEW",
    priority: "HIGH",
    color: "#8b5cf6",
    assigneeName: "정재훈 대리",
    department: "품질팀",
    tags: ["품질", "QA"],
  },
  {
    id: "task-5",
    title: "[경영기획] 9월 전사 월간 업무보고 및 근태 점검",
    description: "주 52시간 준수 현황 및 부서별 일정 진척 보고",
    startDate: "2026-09-11T16:00",
    endDate: "2026-09-11T18:00",
    allDay: false,
    status: "DONE",
    priority: "MEDIUM",
    color: "#64748b",
    assigneeName: "최유진 팀장",
    department: "인사총무",
    tags: ["근태", "보고"],
  }
];
